FROM openjdk:21

RUN apt-get update && apt-get install -y curl unzip zip && \
    curl -s https://get.sdkman.io | bash && \
    bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin"

WORKDIR /app
CMD ["bash"]