name: Build UltraOS

on:
  push:
    branches: [ os ]
  pull_request:
    branches: [ os ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential nasm grub-pc-bin xorriso mtools

    - name: Build ISO
      run: make

    - name: Create new tag
      run: |
        git tag ultraos-latest
        git push origin ultraos-latest

    - name: Create release for tag
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ultraos-latest
        name: OS Build (Latest)
        body: |
          This is the latest build of the `os` branch.
      env:
        GITHUB-TOKEN: ${{ secrets.TOKEN }}

    - name: Upload ISO artifact
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ultraos-latest
        name: OS Build (Latest)
        files: ultraos.iso
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
